/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int Actividad2_2(void);

struct _tipo_mascota{
    char raza[10];
    char nombre[10];
    int edad;
    float peso;
};

struct _tipo_mascota m1;


int main(void)
{

	Actividad2_2();

    /* Loop forever */

}


int Actividad2_2(){
    m1.raza[0] = 'P';
    m1.raza[1] = 'e';
    m1.raza[2] = 'r';
    m1.raza[3] = 'r';
    m1.raza[4] = 'o';
    m1.raza[5] = '\0';

    m1.nombre[0] = 'R';
    m1.nombre[1] = 'o';
    m1.nombre[2] = 'c';
    m1.nombre[3] = '\0';

    m1.edad = 2;
    m1.peso = 10.5f;

    return 0;
}
